#!/bin/bash
#SBATCH --job-name="SC_code"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --mem=120G
#SBATCH --export=ALL
#SBATCH -t 48:00:00

# all SPD matrix files stored in dense column major format
declare -a filearray=(
"../../data/covtype16384.points.bin"
"../../data/mnist16384.points.bin"
"../../data/SUSY16384.points.bin"
"../../data/HIGGS16384.points.bin"
"../../data/HEPMASS16384.points.bin"
)


array=(54, 780, 19, 29, 28)
dim=(19, 176, 12, 26, 24)

rm comtest.csv
rm runtest.csv
executable=./sympiler_proj


  echo "tree&intraction&sample, cogen" > comtest.csv
  echo "sa, compression, evaluation,acc" > runtest.csv
  for filename in "${filearray[@]}"

  do
    d=${array[$i]}
    n=${dim[$i]}
 #   budget=${bg[$i]}

   export OMP_NUM_THREADS=12;
  #budget=0.03
  budget=${1}
  echo "#filename=$filename"

  #for j in {1..3}
  #do
   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d 1e-5 | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d 1e-5 | tee -a comtest.csv

   cd ../matroxTest-V1/

   make

#   ./FMatRoxHGEMM $filename $n $d 1e-1 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-2 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-3 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-4 | tee -a runtest.csv
   ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#
   cd ../sympiler/
 #done
   let i++
  done
  mv ../matroxTest-V1/runtest.csv ./
  paste comtest.csv runtest.csv > sres.csv
