#!/bin/bash
#SBATCH -A mit162
#SBATCH --job-name="SC_code"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 2:00:00

# all SPD matrix files stored in dense column major format
declare -a filearray=(
"../../data/covtype100000.points.bin"
"../../data/HIGGS100000.points.bin"
"../../data/mnist60000.points.bin"
"../../data/SUSY100000.points.bin"
"../../data/letter20000.points.bin"
"../../data/pen10992.points.bin"
"../../data/HEPMASS100000.points.bin"
"../../data/Gas13910.points.bin"
"../../data/grid102400.points.bin"
"../../data/random65536.points.bin"
"../../data/dino8w80000.points.bin"
"../../data/sunflower8w80000.points.bin"
"../../data/unit32000.points.bin"
)


array=(54, 28, 780, 18, 16, 16, 28, 129, 2, 2, 3, 2, 2)
dim=(100000, 100000, 60000, 100000, 20000, 10992, 100000, 13910, 102400, 65536, 80000, 80000, 32000)

rm comtest.csv
rm runtest.csv
executable=./sympiler_proj
  i=0
#  echo "tree&intraction&sample, cogen" > comtest.csv
#  echo "sa, approximation, evaluation,acc" > ../matroxTest-V1/runtest.csv
  for filename in "${filearray[@]}"

  do
    d=${array[$i]}
    n=${dim[$i]}
 #   budget=${bg[$i]}

   export OMP_NUM_THREADS=12;
  #budget=0.03
  budget=0.03
  echo "#filename=$filename"

  #for j in {1..3}
  #do
   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d $budget | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d 1e-5 | tee -a comtest.csv
#   rm *.bin | $executable $filename $n $d 1e-5 | tee -a comtest.csv

   cd ../codeTest/

   make

   ./testHGEMM $filename $n $d 1e-5 $budget 0 | tee -a runtest.csv
   ./testHGEMM $filename $n $d 1e-5 $budget 1 | tee -a runtest.csv
   ./testHGEMM $filename $n $d 1e-5 $budget 2 | tee -a runtest.csv
   ./testHGEMM $filename $n $d 1e-5 $budget 3 | tee -a runtest.csv
 #  ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
 #  ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
 #  ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
 #  ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#   ./FMatRoxHGEMM $filename $n $d 1e-5 | tee -a runtest.csv
#
   cd ../sympiler/
 #done
   let i++
  done
  mv ../codeTest/runtest.csv ./

  awk -F "\"*,\"*" '{print $1, $2}' runtest.csv | xargs -n4 -d'\n' > flops1.csv
  bash datash1
  paste data.csv flops1.csv > h2flops.csv
  rm flops1.csv
