#!/bin/bash
#SBATCH -A mit162
#SBATCH --job-name="SC_code"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --mem=120G
#SBATCH --export=ALL
#SBATCH -t 10:00:00


bash testMatRox 0.0
bash nrhsssh 0.0
bash accsh 0.0
bash testScal 0.0
bash nrunsh 0.0
bash HSSFlops

mkdir HSS
mv *.csv ./HSS/

bash testMatRox 0.03
bash nrhsssh 0.03
bash accsh 0.03
bash testScal 0.03
bash nrunsh 0.03
bash H2Flops

mkdir H2-b
mv *.csv ./H2-b/
