#!/bin/bash

#SBATCH --job-name="Strumpack"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 01:30:00



## all SPD matrix files stored in dense column major format
declare -a filearray=(
"../data/letter20000.points.bin"
"../data/pen10992.points.bin"
"../data/Gas13910.points.bin"
"../data/unit32000.points.bin"
)


array=(16, 16, 129, 2)

if [ -f "stoutput" ]; then
  rm -rf stoutput
fi

executable="./artifact_strumpack.x"

export OMP_NUM_THREADS=12
echo "#@DATE"
date
i=0
for filename in "${filearray[@]}"
do
d=${array[$i]}
echo "#dim=$d"

$executable $filename $d 5 1 1 1 | tee -a stoutput
$executable $filename $d 5 1 1 1024 | tee -a stoutput
$executable $filename $d 5 1 1 2048 | tee -a stoutput
$executable $filename $d 5 1 1 4096 | tee -a stoutput

let i++
done


grep "compression time" stoutput | grep -Eo '[0-9]+[.][0-9]*' > comp.csv

grep "Evaluation time" stoutput | grep -Eo '[0-9]+[.][0-9]*' > eval.csv

paste comp.csv eval.csv > st.csv

awk -F "," '{print $1,$2}' st.csv | xargs -n4 -d'\n' > tst.csv

awk -F ",| " '{print $1,$2}' OFS=, tst.csv > tstrhs1.csv
awk -F ",| " '{print $3,$4}' OFS=, tst.csv > tstrhs1k.csv
awk -F ",| " '{print $5,$6}' OFS=, tst.csv > tstrhs2k.csv
awk -F ",| " '{print $7,$8}' OFS=, tst.csv > tstrhs4k.csv

declare -a tfilearray=(
"letter"
"pen"
"gas"
"unit"
)

rm data.csv
for filename in "${tfilearray[@]}"
do
  echo "$filename," >> data.csv
done


paste data.csv tstrhs1.csv > strhs1.csv
paste data.csv tstrhs1k.csv > strhs1k.csv
paste data.csv tstrhs2k.csv > strhs2k.csv
paste data.csv tstrhs4k.csv > strhs4k.csv

rm tstrhs1.csv
rm tstrhs1k.csv
rm tstrhs2k.csv
rm tstrhs4k.csv
rm data.csv

