#!/bin/bash

#SBATCH -A mit162
#SBATCH --job-name="Strumpack"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 01:30:00



## all SPD matrix files stored in dense column major format
declare -a filearray=(
"../data/letter20000.points.bin"
"../data/pen10992.points.bin"
"../data/Gas13910.points.bin"
"../data/unit32000.points.bin"
)


module load gnu/6.2.0
array=(16, 16, 129, 2)

if [ -f stout ]; then
  rm -rf stout
fi

executable="./artifact_strumpack.x"

echo "#@DATE"
date
i=0
for filename in "${filearray[@]}"
do
d=${array[$i]}
echo "#dim=$d"

    export OMP_NUM_THREADS=1
    $executable $filename $d 5 | tee -a stout

    export OMP_NUM_THREADS=12
    $executable $filename $d 5 | tee -a stout

let i++
done


grep "Evaluation time" stout | grep -Eo '[0-9]*+[.]+[0-9]*' > eval.csv

awk -F "\"*,\"*" '{print $1}' eval.csv | xargs -n2 -d'\n' > tstscal.csv

declare -a tfilearray=(
"letter"
"pen"
"gas"
"unit"
)

rm data.csv
for filename in "${tfilearray[@]}"
do
  echo "$filename," >> data.csv
done

paste data.csv tstscal.csv > stflops.csv

rm tstscal.csv
