#!/bin/bash

#SBATCH --job-name="Strumpack"
#SBATCH --output="ml.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 01:30:00



## all SPD matrix files stored in dense column major format
declare -a filearray=(
"../data/letter20000.points.bin"
"../data/pen10992.points.bin"
"../data/Gas13910.points.bin"
"../data/unit32000.points.bin"
)


array=(16, 16, 129, 2)

if [ -f stout ]; then
  rm -rf stout
fi

executable=./artifact_strumpack.x

export OMP_NUM_THREADS=12
echo "#@DATE"
date
i=0
for filename in "${filearray[@]}"
do
d=${array[$i]}
echo "#dim=$d"
$executable $filename $d 5 | tee -a stout
let i++
done

grep "compression time" stout | grep -Eo '[0-9]+[.][0-9]*' > comp.csv

grep "Evaluation time" stout | grep -Eo '[0-9]+[.][0-9]*' > eval.csv

grep "relative error" stout | grep -Eo '[+-]?[0-9]+([.][0-9]*[e][+-][0-9]*)?' > err.csv

paste comp.csv eval.csv err.csv > stres.csv
